require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WebinarsController do

  # This should return the minimal set of attributes required to create a valid
  # Webinar. As you add validations to Webinar, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WebinarsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all webinars as @webinars" do
      webinar = Webinar.create! valid_attributes
      get :index, {}, valid_session
      assigns(:webinars).should eq([webinar])
    end
  end

  describe "GET show" do
    it "assigns the requested webinar as @webinar" do
      webinar = Webinar.create! valid_attributes
      get :show, {:id => webinar.to_param}, valid_session
      assigns(:webinar).should eq(webinar)
    end
  end

  describe "GET new" do
    it "assigns a new webinar as @webinar" do
      get :new, {}, valid_session
      assigns(:webinar).should be_a_new(Webinar)
    end
  end

  describe "GET edit" do
    it "assigns the requested webinar as @webinar" do
      webinar = Webinar.create! valid_attributes
      get :edit, {:id => webinar.to_param}, valid_session
      assigns(:webinar).should eq(webinar)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Webinar" do
        expect {
          post :create, {:webinar => valid_attributes}, valid_session
        }.to change(Webinar, :count).by(1)
      end

      it "assigns a newly created webinar as @webinar" do
        post :create, {:webinar => valid_attributes}, valid_session
        assigns(:webinar).should be_a(Webinar)
        assigns(:webinar).should be_persisted
      end

      it "redirects to the created webinar" do
        post :create, {:webinar => valid_attributes}, valid_session
        response.should redirect_to(Webinar.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved webinar as @webinar" do
        # Trigger the behavior that occurs when invalid params are submitted
        Webinar.any_instance.stub(:save).and_return(false)
        post :create, {:webinar => { "title" => "invalid value" }}, valid_session
        assigns(:webinar).should be_a_new(Webinar)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Webinar.any_instance.stub(:save).and_return(false)
        post :create, {:webinar => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested webinar" do
        webinar = Webinar.create! valid_attributes
        # Assuming there are no other webinars in the database, this
        # specifies that the Webinar created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Webinar.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => webinar.to_param, :webinar => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested webinar as @webinar" do
        webinar = Webinar.create! valid_attributes
        put :update, {:id => webinar.to_param, :webinar => valid_attributes}, valid_session
        assigns(:webinar).should eq(webinar)
      end

      it "redirects to the webinar" do
        webinar = Webinar.create! valid_attributes
        put :update, {:id => webinar.to_param, :webinar => valid_attributes}, valid_session
        response.should redirect_to(webinar)
      end
    end

    describe "with invalid params" do
      it "assigns the webinar as @webinar" do
        webinar = Webinar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Webinar.any_instance.stub(:save).and_return(false)
        put :update, {:id => webinar.to_param, :webinar => { "title" => "invalid value" }}, valid_session
        assigns(:webinar).should eq(webinar)
      end

      it "re-renders the 'edit' template" do
        webinar = Webinar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Webinar.any_instance.stub(:save).and_return(false)
        put :update, {:id => webinar.to_param, :webinar => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested webinar" do
      webinar = Webinar.create! valid_attributes
      expect {
        delete :destroy, {:id => webinar.to_param}, valid_session
      }.to change(Webinar, :count).by(-1)
    end

    it "redirects to the webinars list" do
      webinar = Webinar.create! valid_attributes
      delete :destroy, {:id => webinar.to_param}, valid_session
      response.should redirect_to(webinars_url)
    end
  end

end
